export enum ActivityType {
    PRICE_MEDIAN_LOW = 'PRICE_MEDIAN_LOW',
    BOTTOM_INTER_MEAN = 'BOTTOM_INTER_MEAN',
    BOTTOM_INTER_MEAN_5_20 = 'BOTTOM_INTER_MEAN_5_20',
    BOTTOM_INTER_MEAN_50_200 = 'BOTTOM_INTER_MEAN_50_200',
    VOLUME_INCREASE = 'VOLUME_INCREASE',
    DAILY_RAISE = 'DAILY_RAISE',
    DAILY_FALL = 'DAILY_FALL',
    HOLE_IN_CHART = 'HOLE_IN_CHART'
}